//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multiplication_Championship.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Awards {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Awards() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multiplication_Championship.Properties.Awards", typeof(Awards).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 1 Completed;Finish the multiplication table of 1 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 1 Conquered;Finish the multiplication table of 1 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A1G {
            get {
                return ResourceManager.GetString("A1G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 1 Dominated;Finish the multiplication table of 1 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A1R {
            get {
                return ResourceManager.GetString("A1R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 2 Completed;Finish the multiplication table of 2 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 2 Conquered;Finish the multiplication table of 2 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A2G {
            get {
                return ResourceManager.GetString("A2G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 2 Dominated;Finish the multiplication table of 2 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A2R {
            get {
                return ResourceManager.GetString("A2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 3 Completed;Finish the multiplication table of 3 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 3 Conquered;Finish the multiplication table of 3 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A3G {
            get {
                return ResourceManager.GetString("A3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 3 Dominated;Finish the multiplication table of 3 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A3R {
            get {
                return ResourceManager.GetString("A3R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 4 Completed;Finish the multiplication table of 4 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 4 Conquered;Finish the multiplication table of 4 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A4G {
            get {
                return ResourceManager.GetString("A4G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 4 Dominated;Finish the multiplication table of 4 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A4R {
            get {
                return ResourceManager.GetString("A4R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 5 Completed;Finish the multiplication table of 5 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 5 Conquered;Finish the multiplication table of 5 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A5G {
            get {
                return ResourceManager.GetString("A5G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 5 Dominated;Finish the multiplication table of 5 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A5R {
            get {
                return ResourceManager.GetString("A5R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 6 Completed;Finish the multiplication table of 6 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 6 Conquered;Finish the multiplication table of 6 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A6G {
            get {
                return ResourceManager.GetString("A6G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 6 Dominated;Finish the multiplication table of 6 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A6R {
            get {
                return ResourceManager.GetString("A6R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 7 Completed;Finish the multiplication table of 7 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 7 Conquered;Finish the multiplication table of 7 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A7G {
            get {
                return ResourceManager.GetString("A7G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 7 Dominated;Finish the multiplication table of 7 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A7R {
            get {
                return ResourceManager.GetString("A7R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 8 Completed;Finish the multiplication table of 8 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 8 Conquered;Finish the multiplication table of 8 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A8G {
            get {
                return ResourceManager.GetString("A8G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 8 Dominated;Finish the multiplication table of 8 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A8R {
            get {
                return ResourceManager.GetString("A8R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 9 Completed;Finish the multiplication table of 9 with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 9 Conquered;Finish the multiplication table of 9 with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A9G {
            get {
                return ResourceManager.GetString("A9G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication of 9 Dominated;Finish the multiplication table of 9 with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string A9R {
            get {
                return ResourceManager.GetString("A9R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Multiplication Completed;Finish any other multiplication table with all the correct answers and without using random or commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string AX {
            get {
                return ResourceManager.GetString("AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Multiplication Conquered;Finish any other multiplication table with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string AXG {
            get {
                return ResourceManager.GetString("AXG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Multiplication Dominated;Finish any other multiplication table with all the correct answers and using random and commutative. The time in seconds cannot exceed twice the number of questions.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string AXR {
            get {
                return ResourceManager.GetString("AXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Correct Answers;Get 100 correct answers in total.
        ///
        ///Correct answer counts prevail across games..
        /// </summary>
        public static string C100 {
            get {
                return ResourceManager.GetString("C100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 Correct Answers;Get 1000 correct answers in total.
        ///
        ///Correct answer counts prevail across games..
        /// </summary>
        public static string C1000 {
            get {
                return ResourceManager.GetString("C1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 Correct Answers;Get 300 correct answers in total.
        ///
        ///Correct answer counts prevail across games..
        /// </summary>
        public static string C300 {
            get {
                return ResourceManager.GetString("C300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnificent Final Challenge;Finish a round using the &quot;All&quot; mode with all the correct answers.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majestic Final Challenge;Finish a round using the &quot;All&quot; mode with all the correct answers and taking 30 seconds or less.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposing Final Challenge;Finish a round using the &quot;All&quot; mode with all the correct answers, using random and commutative and taking 1 minute or less.
        ///
        ///You need to answer at least 20 questions and the minimum value must be greater than 0 if 20 questions are selected..
        /// </summary>
        public static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dazzling Final Challenge;Finish a round using the &quot;All&quot; mode with all the correct answers, using random and commutative and taking 1 minute and 20 seconds or less.
        ///
        ///You need to answer at least 50 questions and the minimum value must be greater than 0 if 50 questions are selected..
        /// </summary>
        public static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time 10 seconds;Finish any multiplication table in 10 seconds or less with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string T10 {
            get {
                return ResourceManager.GetString("T10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time 30 seconds;Finish any multiplication table in 30 seconds or less with all the correct answers and using random and commutative.
        ///
        ///You need to answer at least 10 questions and the minimum value must be greater than 0 if 10 questions are selected..
        /// </summary>
        public static string T30 {
            get {
                return ResourceManager.GetString("T30", resourceCulture);
            }
        }
    }
}
